### ISSUE TITLE
Java 8: DefaultEventListModel should impelement generic ListModel<>

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#595]
<p>In JDK 8 there is generic JList<> with generic ListModel<>. When I write usual (e.g. for JDK6) code such like "actionsList.setModel(new DefaultEventListModel<Action>(actionsClone));" Java 8 shows warning: "Warning:(128, 33) java: unchecked call to setModel(javax.swing.ListModel<E>) as a member of the raw type javax.swing.JList". And if I change raw JList to generic JList<> from some type, warning changes to: "Warning:(371, 30) java: unchecked method invocation: method setModel in class javax.swing.JList is applied to given types<br/>
  required: javax.swing.ListModel<E><br/>
  found: ca.odell.glazedlists.swing.DefaultEventListModel<T>" because of DefaultEventListModel implements raw ListModel.<br/>
The fix shouldnt be very tough...</p>
<i>[GLAZEDLISTS-579] created by realsonic3</i>

**Comment by realsonic** [comment]
@hbrands Hi, you added 1.10.0 milestone. But this is closed issue as suplicate. Should be #594 instead?

**Comment by realsonic** [comment]
And it looks like the issue isn't resolved in 1.10.0... and 1.10.0 in glazedlists_java16 - does it stand for java 1.6?

**Comment by hbrands** [comment]
@realsonic Yes, it's a duplicate of #594 
As 1.10.0 is compiled against Java 1.6, it can't be fixed there.
But I see that JList and ListModel were generified in Java 7,
so we consider it for 1.11 which will be based on Java 7.

**Comment by realsonic** [comment]
@hbrands Thanks!
