### ISSUE TITLE
Migrate build system to Gradle

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#620]
Migrate the ANT-based build to Gradle.
Dependencies should be downloaded from Maven repos.
Restructure and modularize extension source directories and testcases.

Pull request provided by Fabian: GH-16

**Comment by fab1an** [comment]
What additional actions are needed here?

**Comment by hbrands** [comment]
Sorry for the late reply.
(1)
I see the m4 stuff in a separate ant build file. Does that mean, that we'd still need ANT to execute the m4 target? I'd rather have all functionality in the gradle build.
(2)
I think it would make sense to move the io stuff into it's own extension.
(I think NetworkList uses this)
From the ANT build:
io:
include name="**/ctp/**"
include name="**/io/**"
include name="**/nio/**"
include name="**/pmap/**"
include name="**/rbp/**"

**Comment by fab1an** [comment]
The m4 stuff is fixed, I'm now going to move out the io into an own module.

**Comment by hbrands** [comment]
Hi Fabian,
do you know a solution to this problem generating JavaDocs with excludes:
https://discuss.gradle.org/t/javadoc-exclusion-question/11875/4
It seems we have the same problem for the impl packages to be excluded.

**Comment by robeden** [comment]
Do you have a branch for your latest work on that, @hbrands? I can take a look to see if I can help at all.

**Comment by hbrands** [comment]
Hi Rob,
@robeden it's already merged into master...ready to test.

**Comment by hbrands** [comment]
other pull requests merged: #623 , #624 , #627

**Comment by robeden** [comment]
@hbrands - What's the symptom you're seeing? When I run `./gradlew clean javadoc` it blows out with a bunch of errors like:

> /Users/reden/devel/git/third-party/glazedlists/core/src/main/java/ca/odell/glazedlists/swing/EventTableColumnModel.java:171: error: incorrect use of inline tag
    /** @inheritDoc */
        ^

I assume that's not what you're worried about right now?

**Comment by robeden** [comment]
If no one else is working on it, I can clean up those javadoc syntax problems.

**Comment by hbrands** [comment]
I didn't mean those, but they could be fixed, too.
For example, when the docs-target runs I see errors in the io extension like:

`D:\dev\git\glazedlists-master-clone\extensions\io\src\main\java\ca\odell\glazedlists\io\FileList.java:11: error: package ca.odell.glazedlists.impl.io does not exist
import ca.odell.glazedlists.impl.io.Bufferlo;`

and

`D:\dev\git\glazedlists-master-clone\extensions\io\src\main\java\ca\odell\glazedlists\io\ListPeer.java:35: error: cannot find symbol
    private Peer peer;
            ^
  symbol:   class Peer
  location: class ListPeer`

I think that's because we exclude the **/impl/** types in the javadoc task, but Gradle's exclude seems to behave differently in comparison to the javadoc -exclude option.

**Comment by hbrands** [comment]
@robeden - the question is:
Is there a way to "include" the impl-classes/packages, but NOT export the javadoc for them?

**Comment by fab1an** [comment]
#632 Seems to do the trick, it adds the compiled classes to javadocs input.

**Comment by hbrands** [comment]
Yep, I just merged #632. Thanks!

**Comment by hbrands** [comment]
@robeden @fab1an please have a look at issue #635 for publishing artifacts to Maven Central. Let's discuss the publishing issue over there.

**Comment by robeden** [comment]
So, is this all good now?

**Comment by hbrands** [comment]
I think so.
Did you have a chance to test it?
Anyway, we could close this issue and create new ones on-demand if necessary...ok?

**Comment by robeden** [comment]
Test it? Test it!? Of course I tested it!

*/me goes and tests*

For `./gradlew test`, my issue is SWT tests. That's not new, though I'm not seeing an issue for my problem. I'll see if I can get something filed.

For `./gradlew build` I hit:

> :signArchives FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':signArchives'.
> > Cannot perform signing task ':signArchives' because it has no configured signatory
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
> 
> BUILD FAILED

It might be nice to skip that task if not configured. I'll find the sauce for that...

**Comment by robeden** [comment]
I've opened issue #636 for the SWT problems on Mac, though that's really a tracking bug for the [root Gradle issue](https://github.com/gradle/gradle/issues/864) (hey, look: a @fab1an sighting in the wild!).

Anyway, yes... I think this can be closed.

**Comment by hbrands** [comment]
@robeden unfortunately, the Travis build fails now. Please see
https://travis-ci.org/glazedlists/glazedlists/builds

**Comment by robeden** [comment]
Oh, sorry. For some reason I wasn't notified of the failure (or just missed it). Will investigate...

**Comment by robeden** [comment]
Fixed in my branch, which I've now merged to master. 
(Note: I've been having transient Travis failures this morning due to errors downloading from bintray, so a clean built took a couple tries. But the root issue is fixed.)

**Comment by robeden** [comment]
Yup, fixed. ✅

**Comment by hbrands** [comment]
Ok, I think we can consider this done. 
Thanks again for the nice work!
