### ISSUE TITLE
Move publishing artifacts from maven.java.net to Sonatype OSSRH Service

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#635]
The java.net forge closed and maven.java.net seems not operational anymore.
So we'll move to Sonatype OSSRH Service for publishing our artifacts.
See 
http://central.sonatype.org/pages/ossrh-guide.html
http://central.sonatype.org/pages/gradle.html
for details.

We also decided to change Group Id to "com.glazedlists" and Artifact Id to "glazedlists",

**Comment by hbrands** [comment]
With commit 523d936797edfaeb1bd78c2b0d47b58d5428dc49 SNAPSHOT builds already work:
https://oss.sonatype.org/content/repositories/snapshots/com/glazedlists/glazedlists/1.11-SNAPSHOT/

Next up, release builds with signing and uploading.

**Comment by hbrands** [comment]
I'm not sure how to get the signing work together with the maven-publish plugin. For example, the POM also has to be signed before upload.
https://docs.gradle.org/current/userguide/signing_plugin.html
states, that signing the generated POM is not supported yet and Google searches confirm that the new maven publish plugin is not finished in this regard.
The [Gradle OSSRH Guide](http://central.sonatype.org/pages/gradle.html) seems to use the old publish plugin. As I'm not a Gradle expert, what do you suggest?

**Comment by hbrands** [comment]
Further references:
https://discuss.gradle.org/t/how-to-publish-artifacts-signatures-asc-files-using-maven-publish-plugin/7422/18
https://github.com/gradle/gradle/issues/1165

**Comment by hbrands** [comment]
In addition, if I change isSnapshot to false in the gradle.properties, it still uses mavenSnapshotsRepositoryUrl instead of mavenStagingRepositoryUrl when publishing.

**Comment by robeden** [comment]
[Here's a gradle file](https://bitbucket.org/logicartisan/common-core/src/2e41905af3031ac529cbf2f94df592a5a21e0726/build.gradle?at=master&fileviewer=file-view-default) for a project of mine that's publishing to Maven central.

It looks like I'm also using the older "maven" plugin rather than "maven-publish". If I recall correctly, I ended up seeing more benefit sticking with the examples than going with the newer plugin when I implemented things... but I wouldn't be surprised if @fab1an immediately knows how to fix it all. ;-)

**Comment by fab1an** [comment]
Thanks, but unfortunately not in this case. ;)

I don't have experience in publishing to maven, I just copied that part from tutorials. Switching to the old plugin sounds good to me.

@hbrands it's possible that you have to add `== true` to the ternary expression, like how `version` is constructed. Groovy is weird.

**Comment by hbrands** [comment]
Ok, I changed the publishing to use the older maven plugin.
Seems to work now as expected.
