### ISSUE TITLE
Retrofit Glazed Lists functional interfaces with standard functional interfaces (java.util.function) where it makes sense

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#646]
For example:

- **retrofit ca.odell.glazedlists.matchers.Matcher with java.util.function.Predicate**
- **retrofit ca.odell.glazedlists.FunctionList.Function with java.util.function.Function**
- retrofit ca.odell.glazedlists.event.ListEventListener with java.util.function.Consumer
- retrofit ca.odell.glazedlists.Filterator with java.util.function.BiConsumer
- retrofit ca.odell.glazedlists.TextFilterator with java.util.function.BiConsumer
- retrofit ca.odell.glazedlists.TextFilterable with java.util.function.Consumer

**Comment by robeden** [comment]
Guava functional interfaces (Predicate, for example) extend their JDK counterparts. This may be a good way for GL to go also to avoid forcing code changes.

**Comment by hbrands** [comment]
For now, I decided to implement only the first two.
For example, Filterator and TextFilterator are both implemented by BeanTextFilterator. If they both where to implement BiConsumer, we get the following compile problems (in Eclipse) for BeanTextFilterator:

- Name clash: The method accept(List<C>, E) of type Filterator<C,E> has the same erasure as accept(List<String>, E) of type TextFilterator<E> but does not override it	

- The interface BiConsumer cannot be implemented more than once with different arguments: BiConsumer<List<D>,E> and BiConsumer<List<String>,E>

Likewise, if ListEventListener would implement Consumer, this could break any implementation class which already implemented Consumer somehow.

Therefore, we should do this only where it really makes sense and provides benefits.

**Comment by hbrands** [comment]
I'm not sure, if we should override the default methods in Matcher to change the return type like:

```
    default Matcher<E> and(Predicate<? super E> other) {
        Objects.requireNonNull(other);
        return (t) -> test(t) && other.test(t);
    }
    
    default Matcher<E> or(Predicate<? super E> other) {
        Objects.requireNonNull(other);
        return (t) -> test(t) || other.test(t);
    }

    default Matcher<E> negate() {
        return (t) -> !test(t);
    }
```

So you could chain Predicates and Matchers and treat the result as Predicate or Matcher.
@robeden do you see any problems in doing so?

**Comment by hbrands** [comment]
Closing this for 1.12.
No further changes planned for this release.
