### ISSUE TITLE
EventList: provide new default methods for Lock-Management

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#647]
decide on useful API methods, something like:

default void acceptWithReadLock(Consumer<EventList<E>> consumer) {...}
default void acceptWithWriteLock(Consumer<EventList<E>> consumer) {...}

default <R> R applyWithReadLock(Function<EventList<E>, R> function) {...}
default <R> R applyWithWriteLock(Function<EventList<E>, R> function) {...}

**Comment by robeden** [comment]
It would be good to write some JMH benchmarks before using this widely. I haven't seen this pattern widely used, which surprises me if it's lightweight from a performance standpoint. I wouldn't be surprised if it bypasses some JIT optimizations.

**Comment by fab1an** [comment]
Not exactly ontopic, but it has been on my mind for a while: I structure newer applications usually in a way that only one thread is responsible for the glazed lists. Access from other threads is done  via actorstyle message-passing and if the thread is too slow I work around it on a higher application level.

So for me a completely lock-free version would suffice (and possibly bring performance).  

I wonder if a core api without locking mechanisms could be extracted out.

That was also open the possibility of compiling GL to javascript.

**Comment by robeden** [comment]
You could provide a no-op lock implementation to the base list. All other lists in the chain would share it. For most operations you can simply ignore the lock should you wish, though there are a few where locking is done in the framework.

**Comment by fab1an** [comment]
Thanks for the pointer, I'll look into this at some point.

**Comment by robeden** [comment]
@fab1an - Are you planning to do this with your benchmarks module? If not I can whip one up.

**Comment by fab1an** [comment]
No time for that yet, i just added the module for convenience (took me a while to figure out a simple buildscript for jmh). 

When I can spare time to work on GL i‘ll take a look at the ignored failing unittests next.

**Comment by fab1an** [comment]
If you can do something, that would be cool. 

I wonder about CompositeList. It needs to share Lock and ListEventPublisher at the moment, is only the publisher required then?

**Comment by hbrands** [comment]
I added the four mentioned default methods as experimental API.
I want to get a feeling if and how it will simplify our code.

**Comment by hbrands** [comment]
Current state of API:
default methods in EventList interface:

default void acceptWithReadLock(Consumer<EventList<E>> consumer)
default void acceptWithWriteLock(Consumer<EventList<E>> consumer)
default <R> R applyWithReadLock(Function<EventList<E>, R> function)
default <R> R applyWithWriteLock(Function<EventList<E>, R> function)


Helper methods in new Guard class:

public static <E, L extends EventList<E>> void acceptWithReadLock(L eventList, Consumer<L> consumer)
public static <E, L extends EventList<E>> void acceptWithWriteLock(L eventList, Consumer<L> consumer)
public static <E, L extends EventList<E>, R> R applyWithReadLock(L list, Function<L, R> function)
public static <E, L extends EventList<E>, R> R applyWithWriteLock(L list, Function<L, R> function)

The default methods in the EventList interface only expose the EventList type to the Consumer or Function, so list implementation class methods are not available in this case.

The guard class exposes the concrete EventList implementation type to the Consumer or function,
so more methods are usable in this context (see examples in GuardTest). To enable the same flexibility in the default methods we would have to use  [Self-bounding generics](https://stackoverflow.com/questions/22802268/java-default-method-get-type-of-subclass) which is not desirable I think.

**Comment by hbrands** [comment]
No more changes planned for the next version.
