### ISSUE TITLE
SeparatorList: performance optimization in method listChanged

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#648]
The second pass iterating over the source list changes is very inefficient when therer are large groups per separator and a lot of list changes affect the same group. In this case method
updateGroup(int group, int groupCount, boolean fireEvents) 
is called many times for the same group which is inefficient because of iterating over the group elements.

Performance could be optimized by calling the updateGroup method only when needed.
This can be achieved in the second pass by first determining the groups that need an update.
When all list changes have been considered and the affected groups have been marked, then the group update should happen. This way any group is only updated once instead of many times.

**Comment by fab1an** [comment]
Offtopic, but what is the typical usecase for separatorlist?

**Comment by hbrands** [comment]
It's basically a grouping of list elements by a comparator combined with injecting separators into the list for each group. 
This can be the basis for creating dedicated gui components like the separator table in the issue browser demo. The separator could be used to display some summary information about each group.
