### ISSUE TITLE
Release version 1.11

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#649]
- [x] ensure all planned issues are fixed and master branch is current and valid
- [x] create release branch glazedlists-1.11.x from master
- [x] in release branch adjust version settings in gradle.properties and commit
- [x] in release branch do final testing locally
- [x] in release branch upload archives to Nexus OSS
- [x] login to Nexus OSS and examine staging repo
- [x] close staging repo in Nexus OSS
- [x] push release branch to GitHub
- [x] do final testing on release artifacts from staging repo: https://oss.sonatype.org/content/groups/staging/com/glazedlists/glazedlists/1.11.0/
- [x] tag release branch "v1.11.0"
- [x] push new tag to GitHub
- [x] release staging repo in Nexus OSS for sync with Maven Central
- [x] comment on ticket OSSRH-32196 that first release was promoted
- [x] when release is available in Maven Central do final sanity checking
- [x] update Glazed Lists site for new release and make annoucement
- [x] in release branch glazedlists-1.11.x adjust version settings in gradle.properties for next possible bugfix release (1.11.1-SNAPSHOT)
- [x] commit and push changes in release branch
- [x] in master adjust version settings in gradle.properties for next release (1.12.0-SNAPSHOT)
- [x] commit and push changes in master

**Comment by hbrands** [comment]
@robeden @fab1an @sberul @jplemieux @swankjesse 
please sanity check staged artifacts for Glazed Lists 1.11 available here:
https://oss.sonatype.org/content/groups/staging/com/glazedlists/glazedlists/1.11/
Let me know any problems you find. Thanks!

**Comment by fab1an** [comment]
Version 1.10 has 

Include-Resource: resources=resources

in the MANIFEST, while 1.11 has

Include-Resource: resources=core/src/main/resources/resources

Not sure if that's something?
Fabian

**Comment by sberul** [comment]
Looks like my changes were merged in correctly, I don't see any problems.
Thanks!

**Comment by hbrands** [comment]
@fab1an I didn't find the "Include-Resource" manifest header in the OSGi specification, so I don't think it's used at runtime. It seems the bnd tool uses it to include resources from the file system in the jar.

**Comment by fab1an** [comment]
Alright, thanks for checking.

**Comment by robeden** [comment]
@hbrands - I see the snapshot is version "1.11". Will we be using normal [semantic versioning](semver.org), i.e., "1.11.0"?

**Comment by robeden** [comment]
Hey @fab1an, you should join us on Gitter, btw. https://gitter.im/glazedlists/glazedlists

**Comment by hbrands** [comment]
@robeden in maven terms 1.11 is the same as 1.11.0 as maven will strip trailing "nulls".
But you're right, for consistency with older versions like 1.10.0 we should explicitly name it 1.11.0.

**Comment by hbrands** [comment]
Ok, it's restaged here:
https://oss.sonatype.org/content/groups/staging/com/glazedlists/glazedlists/1.11.0/
Sorry for the inconvenience.
I'll release tomorrow unless a showstopper comes up.

**Comment by fab1an** [comment]
@robeden Chat never worked well for me when coding, i keep forgetting checking the messages ;).

**Comment by robeden** [comment]
Yeah, I hear you. You can set Gitter up to email you... though that can be annoying. It just would be nice to have a better place for general discussion. We can use the mailing list, but that seems so 1990's. 😜

**Comment by fab1an** [comment]
I'm testing 1.11 from Mavencentral in our product now, so far no issues.

**Comment by fab1an** [comment]
@robeden I also don't check emails all the time :). Yeah, maybe the problem is that chatrooms always get so full. There should be a gitter with room-size-limitation of 5 or something.

**Comment by hbrands** [comment]
Release is done.

**Comment by fab1an** [comment]
Awesome, GlazedLists goes 2018. Thank you Holger.
