### ISSUE TITLE
Review and convert useful Japex benchmarks to JMH benchmarks

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#655]
We have some old Japex benchmarks that should be reviewed.
If they are still useful, migrate them to the JMH benchmark module.

For example, the ListEventPublisherPerformance-Test is obsolete.
The Sortedlist- und ThreadProxyList-Test might still be interesting.

The goal is to finally remove the Japex extension and dependency.

**Comment by hbrands** [comment]
ThreadProxyList and SortedList benchmarks + supporting classes were
reimplemented with jmh.
ListEventPublisher benchmark was obsolete and deleted.
Japex extension was deleted.

**Comment by fab1an** [comment]
Thank you.
