### ISSUE TITLE
Add Automatic-Module-Name to Manifest

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#656]
Reasoning:
http://branchandbound.net/blog/java/2017/12/automatic-module-name/
Naming modules:
http://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html
Automatic modules:
http://blog.joda.org/2017/05/java-se-9-jpms-automatic-modules.html

We have to decide on a proper module name, for example

- ca.odell.glazedlists
- ca.odell.glazedlists.glazedlists-all
- com.glazedlists
- com.glazedlists.glazedlists-all
- ???

**Comment by robeden** [comment]
I would personally like to consider spinning some or all of the extensions into their own maven artifacts (reduce core size and dependencies). If this is something other people are interested in, we’ll want to keep it in mind when designing our modules.

**Comment by hbrands** [comment]
Yes, we can consider this. But splitting up true modules also involves avoiding split packages for example. I think moving around classes and creating new maven artifacts is something for a major release in my opinion.
Until we are there, my intention was to provide a module name for the "monolithic" artifact, so users who want to modularize their applications can start using a stable module name.
(Of course, the "modularized" Glaed Lists version would have different module names in the future)

So, I'm seeking a module name for the one artifact we have right now.
But for 1.12 we should discuss and decide if and what extensions we would like to deprecate. I'll open a separate issue for that aspect.

**Comment by robeden** [comment]
Yeah, I see what you mean. I had thought our packages were better nested, but I see that you're right. It looks like Hibernate, JavaFX and NachoCalendar would be easy to do, but that's about it.

**Comment by hbrands** [comment]
We could also try to extract a swing extension from the core and then merge a few extensions. For example, the calculation and the treetable extension don't add further external dependencies and could be merged into core and swing then. So we have some options here. I'll open a separate issue for the modularization effort.

**Comment by hbrands** [comment]
So now we could choose a module name like
com.glazedlists.glazedlists-all

and later for the real modules something like
com.glazedlists.glazedlists-core
com.glazedlists.glazedlists-swt
com.glazedlists.glazedlists-javafx
...

Or do you like the package name as prefix better?
(That raises the question if we should change the root package to com.glazedlists.* at some time in the future?)

**Comment by hbrands** [comment]
@robeden @fab1an 
So, I propose that we now use the module name
com.glazedlists.glazedlists-all
for the big uber jar we have now.
It's more oriented towards the maven coordinates, because it avoids confusion if we'd decide to rename root package to 'com.glazedlists' later.
The '-all' suffix emphasizes the fact that the artifact isn't really modularized yet. But providing this automatic module name now is better than leaving the default (derived from the JAR filename).

Please let me know any concerns soon else I'll proceed with the proposal for 1.12.0.

**Comment by robeden** [comment]
To be honest, I haven’t studied module naming enough to feel like I can give a good review. But, your reasoning sounds good to me.

**Comment by fab1an** [comment]
Good idea.

**Comment by robeden** [comment]
May want to consider this:
http://blog.joda.org/2018/03/jpms-negative-benefits.html

**Comment by fab1an** [comment]
Thanks for digging that up Rob. With some effort we can (and should) configure gradle to set up these tests. 

Also I think that problem will gain wider recognition over time, so maybe Oracle will look into it. 

If this issue affects a user of GL and said user reports it we should be able to create a kind of build-UnitTest for the bug. A bit meta, but probably worthwile.

**Comment by hbrands** [comment]
Yes, interesting summary. I agree that we have to test Glazed Lists on the module path at some point.

But currently, a user can put a JAR on the classpath or module path irrespective of the existence of an Automatic-Module-Name, so most of the listed problems are (or should be) unrelated to this manifest entry. It only implies a different module name, **if** the artifact is put on the module path, nothing more.
IDEs and build tools should not imply more IMO.
For example, it doesn't mean that it correctly works on the module path, only the documentation can tell, so we should document the current state when we release the next version.

**Comment by fab1an** [comment]
What do you think about this: We could provide a glazedlists-debug.jar, if necessary as a javaagent that loads GL and enables us to use all kinds of hacks like modifying the classloader and read the java version to check for module-path bugs or else. 
This could also automatically insert DebugLists for BasicEventLists.

**Comment by hbrands** [comment]
Because of the linked article from the joda blog, which contains some interesting reasoning,  I abstain from adding an Automatic-Module-Name for version 1.12.
**Close as Won't fix**
