### ISSUE TITLE
Deprecate outdated extensions

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#658]
We should agree upon which extensions we would like to deprecate from 1.12 onward.

Deprecated extensions will become unsupported and eventually be removed from the Glazed Lists distribution.

My personal proposal for deprecation is:
- nachocalendar
- ktable
- jgoodiesforms

(NachoCalendar and KTable seem to be quite old and unsupported themselves. I think for SWT users nowadays Nebula NatTable is the recommended table widget which features its own integration.
I assume the JGoodies extension isn't used widely, too.)

WDYT?

**Comment by robeden** [comment]
🤷‍♂️ Back in my Swing days I used JGoodies a lot, but never the GL extension. That's the sum of my –not very useful– knowledge.

**Comment by robeden** [comment]
Does anyone use the `io` stuff? I'd love to see that gone.

**Comment by fab1an** [comment]
I agree.

**Comment by hbrands** [comment]
I don't use the io stuff either.
There are three main lists: FileList, NetworkList and CachingList
I think CachingList is not so "heavy" as the first two. May be we can move CachingList to the core and deprecate the rest of the io extension?

**Comment by robeden** [comment]
CachingList is interesting, definitely. I've never come across it before (probably because it's in the `io` package).

**Comment by hbrands** [comment]
@robeden @fab1an 
So my proposal for version 1.12.0 is to deprecate the following extensions:

- nachocalendar*
- ktable
- jgoodiesforms
- io*

That means every type in these extensions (and impl. types in core or other extensions that are used in the deprecated extensions exclusively) will be deprecated. In addition

- As NachoDateRangeMatcherEditor is used in the issue browser I will add a note that it will be moved to the issue browser module in a later version when the nachocalendar extension will be removed officially. It basically means that it's not supported anymore, but can still be used from the issue browser, analog to the JSeparatorTable which is available only in the issue browser demo.

- CachingList from io (and its impl. types) will not be deprecated, but gets a note that it will be moved to core in a later version when the io extension will be removed officially.

If there are no objections, I'll proceed soon...

**Comment by robeden** [comment]
👍

**Comment by fab1an** [comment]
Since 1.12 isn’t a bugfix release, why not move CachingList immediately?

**Comment by hbrands** [comment]
CachingList lives in package _ca.odell.glazedlists.io_ right now.
Moving it to core and avoiding further split packages means to change its package to _ca.odell.glazedlists_, which would be an incompatible change (in a minor release).
While I'm not always so strict with regard to semver.org rules, I think there is little benefit to move it for 1.12.0 already.
