### ISSUE TITLE
Question: How to implement a TableFormat with dynamic columns?

### ISSUE THREAD

**Issue by BigChief45** [glazedlists/glazedlists#664]
The examples on creating a `TableFormat` show implementations of a fixed `getColumnCount()`, a `getColumnName()` and `getColumnValue()` using if/switch statement to return an appropriate value.

However let's say that I want to create my JTable based on CSV files that contain different columns, yet my Bean object contains the fields for _**all**_ possible columns. This means that I cannot return a fixed value for `getColumnCount()`, and I cannot use an if/switch statement in the other methods because the column index received can indicate a differenet column depending on the file.

What would be the best approach to tackle this issue?

**Comment by hbrands** [comment]
You probably have to create your own TableFormat implementation that takes your CSV column descriptors as a parameter. e.g. you read in your CSV file, determine the columns and pass this info into your TableFormat.

Please raise these kind of questions on our [Gitter chat](https://gitter.im/glazedlists/glazedlists) or on [Stackoverflow](https://stackoverflow.com/questions/tagged/glazedlists) with the tag "glazedlists".
This issue tracker is not intended for user questions.
Thanks.
