### ISSUE TITLE
Deadlock in GEventDataModel

### ISSUE THREAD

**Issue by LilianValero** [glazedlists/glazedlists#667]
Hi, it seems that FilterList.changeMatcherWithLocks leads to deadlock in certain cases:
-  Waiting  on java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync@2819a0cb
    at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(AbstractQueuedSynchronizer.java:1199)
    at java.util.concurrent.locks.ReentrantReadWriteLock$WriteLock.lock(ReentrantReadWriteLock.java:943)
    at ca.odell.glazedlists.util.concurrent.LockAdapter.lock(J2SE50LockFactory.java:85)
    at ca.odell.glazedlists.FilterList.changeMatcherWithLocks(FilterList.java:274)
    at ca.odell.glazedlists.FilterList.setMatcher(FilterList.java:126)

It appears that the pattern:
getReadWriteLock().readLock().lock();
try {
... } finally {
getReadWriteLock().readLock().unlock();  
}
is not threadsafe and so can lead to deadlock. It appears safer to use the following pattern:
final Lock readLock= getReadWriteLock().readLock();
readLock.lock();
try {
... } finally {
readLock.unlock();  
}
Same thing for getReadWriteLock().writeLock() calls. There are around 90 calls on readLock() which need to be reviewed and 80 calls on writeLock() which need to be reviewed too.
TIA

**Comment by robeden** [comment]
Hi @LilianValero.

> It appears that the pattern:
> getReadWriteLock().readLock().lock();
> try {
> ... } finally {
> getReadWriteLock().readLock().unlock();
> }
> is not threadsafe and so can lead to deadlock.
> [...]

Technically, you could be correct as the documentation does not guarantee that the Lock instance returned from the EventList never changes. However, in reality Lock instances (in built-in EventList implementations) are effectively final*. Once set in the constructor they are never changed. So, the above pattern *is* safe to use for built-in list implementations. If you have a custom implementation that does not treat the lock as final, I highly recommend you change your implementation. I will add a clarifying stanza to the method documentation.


As far as the assertion that "FilterList.changeMatcherWithLocks leads to deadlock in certain cases"... can you please provide a test case or at a minimum stack traces from the conflicting threads? A trace from one thread is insufficient to prove there is a deadlock. The trace you show simply indicates that it is waiting for a read lock, which is a completely normal situation.

**Comment by LilianValero** [comment]
Thanks for your answer. The issue is still under investigation on our side. I let you know if it is a real issue or not on your side.

**Comment by LilianValero** [comment]
After investigation, the deadlock was not caused by this pattern. So I'm sorry for the false alarm.

**Comment by robeden** [comment]
Thanks for the update.
