### ISSUE TITLE
Explore Azure Pipelines for CI builds to additionally support Mac and Windows builds

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#671]
JUnit announced recently their switch to Azure Pipelines:
https://www.infoq.com/news/2019/03/junit-azure-pipelines

Let's explore Azure Pipelines for Glazed Lists as well to support Windows and Mac Os builds besides Linux.

I've created an azure-integration branch for testing and configuring the build. See azure-pipelines.yml and build-job.yml.

**Comment by hbrands** [comment]
Azure uses OpenJDK builds from Azul, so this is also a good test.
But Azul OpenJDK 8 build is not a drop-in replacement for Oracle JDK 8, as the former does not include JavaFX but the latter does.
So for the time being our Azure builds work with Java 11 and above when available.

**Comment by hbrands** [comment]
@robeden I played around with Azure Pipelines as an additional CI provider in this branch:
https://github.com/glazedlists/glazedlists/tree/azure-integration
See here:
https://dev.azure.com/glazedlists/glazedlists/_build/latest?definitionId=1&branchName=azure-integration
For now, I set up Ubuntu, Windows and Mac OS builds with Azul Java 11.

Please let me know what you think of it.

**Comment by robeden** [comment]
I have a TeamCity server at home which you can use if you’d like another option.

**Comment by robeden** [comment]
Is there a cost for us to use Azure pipelines?

**Comment by hbrands** [comment]
I don't think so:
https://azure.microsoft.com/en-us/pricing/details/devops/azure-pipelines/
Open source projects have a free plan.
What bothered me is, that we had no proper Windows and Mac builds.

**Comment by hbrands** [comment]
Fixed by pull request  #681 .
