### ISSUE TITLE
Add Travis CI build for OpenJDK 11 (and 12)

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#672]
Java 11 is a LTS release that we'll need to support. As Oracle JDK is no longer usable for free in commercial projects the recommended Java environment is now Open JDK 11.

We need to add a Travic CI build for it.
Things to consider:

- Gradle support for Java OpenJDK 11
- integrate JavaFX as an external dependency

Getting Started with JavaFX 11 for Gradle 4.10+ : https://openjfx.io/openjfx-docs/#gradle

**Comment by hbrands** [comment]
Ok, thanks!
Then I'll have a look at the Windows build.

**Comment by hbrands** [comment]
Of course, if we find issues within GlazedLists with regard to OpenJDK 11, we can create additional issues adressing those...

**Comment by robeden** [comment]
After taking WAY too long to remember to do this, I've finally added the configuration in 1d96087b447c4ae3f3aa2f528a44fc3bf2fd542d (currently in a branch).

I've updated the JDKs to be used to:
- Oracle JDK 8
- OpenJDK 11
- OpenJDK "EA" (presumably 12 at this point, though should be updated as time goes on)

I'm seeing failures, but I'm seeing failures on the JDK 8 build as well.
See: https://travis-ci.org/glazedlists/glazedlists/builds/485173404

This test fails across all JDKs:
> ca.odell.glazedlists.swing.DefaultEventListModelTest > testOnMainThreadNoEDTViolation FAILED
    java.lang.AssertionError at DefaultEventListModelTest.java:61

Seeing as the builds worked the last time this code was run on Oracle JDK 8, I'm assuming something changed with the Travis environment to break it, but I haven't looked into it yet for more details.

@hbrands : Would you prefer I merge this change in as-is and create a new issue for the test failure or would you rather figure this out on the branch?

**Comment by hbrands** [comment]
@robeden I'll need to take a look at the JDK 8  build failure.
But for JDK 11 and above there are different errors I think. Looks to me as if Gradle can't parse the Java version. I guess we need Gradle version 4.10+
Also, for OpenJDK we probably need to include the JavaFx dependencies explicitly: https://openjfx.io/openjfx-docs/#gradle
I think we should fix the major issues on this branch before merging...

**Comment by robeden** [comment]
@hbrands : Oh, thanks for pointing that out. I hit the JDK 8 errors and stopped digging. Yes, you're right... the JavaFX stuff will be needed.

**Comment by hbrands** [comment]
I think I fixed the JDK 8 build failure (locking issue in multi-thread scenario).

But Gradle 4.10.x won't be enough for Java 11 support. I ran into issue
https://github.com/gradle/gradle/issues/8058
We need Gradle 5.x.

**Comment by robeden** [comment]
Thanks for fixing that. Sorry I've been such a deadbeat getting that done. 😕

We've been using Gradle under Java 11 for some time without issue. That issue seemed short on info, do you know what the root cause is? I'll look at our test environment a bit and see if I can figure out what the difference is.

**Comment by hbrands** [comment]
No problem. I had some time today, so I had a look.

The issue with Gradle 4.10.x and Java 11 (and JUnit 4.11?) seems to be that all classes in /src/test/java are considered as test classes, even helper and nested classes. This leads to all sorts of errors such as public constructor missing, no test methods found ...

**Comment by hbrands** [comment]
I'm experimenting with Gradle 5.0 right now. After upgrading some plugins (capsule, bnd), this seems to work better on Java 11 (not addressing javafx problem yet).
What's your preference for the Gradle version?

**Comment by robeden** [comment]
Oh, maybe it's JUnit 4 related. We've switched to 5. Maybe that migration would be worth it.
(We're using 4.9 in the first JDK 11-based project I checked.)

**Comment by robeden** [comment]
Of course, updating to Gradle 5 isn't bad is we're not using any deprecated pieces.

**Comment by robeden** [comment]
We're still on Gradle 4.x, though going to 5 is fine with me.
I'll look at that JavaFX issue. Are you still in the original branch?

**Comment by hbrands** [comment]
The problem with JUnit 5 is this open issue:
https://github.com/junit-team/junit5/issues/157
We currently run a lot of tests on the Swing thread.

I made the fix for the JDK 8 build failure on the branch "672-jdk11-ci".
The Gradle 5 changes are not committed yet.

**Comment by hbrands** [comment]
I committed my changes for Gradle 5 to branch "672-jdk11-ci" now.
For now, I commented out the sub projects dependent on JavaFx for Java 11 and 12 in settings.gradle, such that the Travis builds are green.

**Comment by robeden** [comment]
Yeah, I haven't been able to get JavaFX to compile under 11 in a way that will be compatible with Java 8. I haven't done JavaFX development in a while so I'm out of the loop. 🤷‍♂️

**Comment by hbrands** [comment]
@robeden I upgraded to Gradle 5.3.1 and merged the changes back into master.
