### ISSUE TITLE
Using class LatinDiacriticsStripper

### ISSUE THREAD

**Issue by Rado9** [glazedlists/glazedlists#674]
Hi,
how can I use class LatinDiacriticsStripper.java in my project?
https://github.com/glazedlists/glazedlists/blob/master/core/src/main/java/ca/odell/glazedlists/impl/text/LatinDiacriticsStripper.java

From this class:
   
```
/**
     * This method strips diacritics from latin characters, which allows fuzzy
     * matching between languages. For example, the mapped value of é is e.
     * So, the word "résumé" could be matched by simply typing "resume".
     *
     * @return the normalized version of <code>c</code>, which can be any character
     */
    public static char[] getMapper() {
        return MAPPER;
}
```

From my project:

```
final EventList<SItem> eventList = GlazedLists.eventList(Arrays.asList(allItems));
cb.setModel(new DefaultComboBoxModel<>(allItems));
AutoCompleteSupport.install(cb, eventList);
```

I cannot find any example.
Thanks

**Comment by hbrands** [comment]
@Rado9 So you want to use the functionality of LatinDiacriticsStripper in the AutoCompleteComboBox?
LatinDiacriticsStripper is an internal implementation class as the package "ca.odell.glazedlists.impl" indicates. Those classes should not be used directly in user code.
But you can effectively use it by specifying a text matching strategy for your AutoCompleteSupport,
in particular the normalized strategy as below:

`AutoCompleteSupport support = AutoCompleteSupport.install(cb, eventList);
support.setTextMatchingStrategy(TextMatcherEditor.NORMALIZED_STRATEGY);
`
Please see the Javadoc for AutoCompleteSupport#setTextMatchingStrategy, TextMatcherEditor and TextMatcherEditor#NORMALIZED_STRATEGY.

I hope this answers your question.

**Comment by Rado9** [comment]
@hbrands It works. Thanks :)
