### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by DarioRomano** [glazedlists/glazedlists#680]
Hello, we want to use glazedlists in a product that may become open source, with a proprietary version for internal use.
We were using an older version of glazedlists which was still licensed under MPL1.1 which is not compatible with the GLPL licensing we want to go with.
I've recently updated to the current version of glazedlists, which contains a link to mozillas MPL information page which would indicate, that the curent version of glazedlists is published (partly) under MPL 2.0).
When checking on [mvnrepository](https://mvnrepository.com/artifact/com.glazedlists/glazedlists) though, it says it's still licensed under MPL1.1 .
Unfortunately I couldn't find any further notice in the .jar file or sources, just the link. 
Under which license was glazedlists 1.11.0 published?

Thanks in advance!

**Comment by robeden** [comment]
Hi @DarioRomano. GL 1.11 was published under the same dual-licensing scheme still used. It is published under both the MPL and LGPL (2.1). You may choose whichever serves your purposes best.

1.11 link: https://github.com/glazedlists/glazedlists/blob/glazedlists-1.11.x/license
Current link: https://github.com/glazedlists/glazedlists/blob/master/license

If you need any further clarification, please let us know.

**Comment by DarioRomano** [comment]
Thanks for the clarification, this has been very helpful!
Although the link you're providing in the license file packaged with the source and binaries is somewhat misleading. The current link for MPL is pointing to the information page for MPL2.0, which is apparently way better in terms of compatability with other licenses.

**Comment by robeden** [comment]
I agree the version of MPL is not specified sufficiently. I'll try to get that clarified with the team.
