### ISSUE TITLE
Broken links on "maven" page on website

### ISSUE THREAD

**Issue by apjanke** [glazedlists/glazedlists#685]
Hi, Glazed Lists folks,

On the "maven" page on the project website - http://www.glazedlists.com/Home/maven - the links for "Maven central repository" and "SNAPSHOT REPO" are broken.

The "Maven Central repository" link, pointing to http://repo1.maven.org/maven2/com/glazedlists/glazedlists/, gives me an "HTTPS Required" error:

```text
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required
```

The "SNAPSHOT REPO" link, pointing to https://oss.sonatype.org/content/repositories/snapshots/, gives me a Forbidden error:

```text
Directory listing forbidden
```

Is the Glazed Lists website in a repo somewhere, so I can submit a PR for this?

**Comment by hbrands** [comment]
Thanks for the info!
It should be fixed now.

**Comment by apjanke** [comment]
Works for me now! Thanks.
