### ISSUE TITLE
working with and developing glazedlists. Community?

### ISSUE THREAD

**Issue by errael** [glazedlists/glazedlists#693]
The project seems abandoned. (I'm going to look through the forks, but ...)

I'm going to work on a fix for #676. I'm wondering if the project might be active in some other location.

I'm basing my fix on 1.11.0. I was tempted to back up to 1.10.0 since I have no gradle experience. Could go with 1.12 snap, but I wonder about stability; it looks mostly like jdk1.8+ support.

Any insights appreciated.

**Comment by hbrands** [comment]
Hi,
this is the main project for Glazed Lists.
There are a few maintainers who work on Glazed Lists in their free time.
There has not been much activity in the last months, but it's not abandoned.
We intend to release version 1.12 "soonish", which is currently on the master branch.
It's quite stable, I'm using it in a very big production application for example.
So I suggest to base your work on master. Thanks!
Holger

**Comment by errael** [comment]
I'm using Netbeans. I can open/edit/debug core, but I can't run individual tests from NetBeans. For example I copied AutoCompleteSupportTestApp to a separate NetBeans project and can run/debug that way. If I open other subprojects, for example extensions/icu4j, when I open a file, GlazedListsICU4J.java for example, the imports that resolve into the "core" jar are not found (error highlights from IDE). I'm investigating this from the NetBeans side.

I suspect the rather archaic build.gradle files are at the root of the issue. I want to add some tests for AutoCompleteSupport. The tests of interest are in extensions/icu4j, for example AutoCompleteSupportTest. I'm not doing anything in particular with icu4j, but that's where the test is.

Since this is the first project I've worked with that uses gradle, I'm at more of a loss than usual. Any hints or suggestions appreciated.

**Comment by errael** [comment]
"./gradlew build --scan" produced https://gradle.com/s/iwj7ksmm72wc2 with deprecation
```
The configuration :extensions:compileClasspath was resolved without accessing the project in a safe manner.
```
This seems related to the type of problem I'm having, so I'll see what I can see. The deprecation warning suggested looking at
```
https://docs.gradle.org/5.3.1/userguide/troubleshooting_dependency_resolution.html#sub:configuration_resolution_constraints
```

**Comment by hbrands** [comment]
> I'm using Netbeans. I can open/edit/debug core, but I can't run individual tests from NetBeans. For example I copied AutoCompleteSupportTestApp to a separate NetBeans project and can run/debug that way. If I open other subprojects, for example extensions/icu4j, when I open a file, GlazedListsICU4J.java for example, the imports that resolve into the "core" jar are not found (error highlights from IDE). I'm investigating this from the NetBeans side.
> 
> I suspect the rather archaic build.gradle files are at the root of the issue. I want to add some tests for AutoCompleteSupport. The tests of interest are in extensions/icu4j, for example AutoCompleteSupportTest. I'm not doing anything in particular with icu4j, but that's where the test is.
> 
> Since this is the first project I've worked with that uses gradle, I'm at more of a loss than usual. Any hints or suggestions appreciated.

Sorry, I'm not familiar with Netbeans, I'm a Eclipse user. Usually there are IDE plugins for supporting build tools, like m2e for Maven support and Buildship for Gradle support in Eclipse. 
I assume there is some kind of plugin for Gradle support in Netbeans, too. A quick Google search revealed this link:
https://netbeans.org/features/java/build-tools.html
Hope this helps.
