### ISSUE TITLE
Remove travis-ci build support

### ISSUE THREAD

**Issue by hbrands** [glazedlists/glazedlists#703]
Given recent (and not so recent) developments around travis-ci I propose to end building Glazed Lists with travis-ci.
Instead we should focus on CI builds via Github Actions.

References:

https://arstechnica.com/information-technology/2021/09/travis-ci-flaw-exposed-secrets-for-thousands-of-open-source-projects/

https://travis-ci.community/t/security-bulletin/12081

https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

https://blog.travis-ci.com/2021-05-07-orgshutdown

**Comment by hbrands** [comment]
We would need to remove .travis.yml und the Badge from the readme file.

Ideally, we should also remove the connection between the Glazed Lists Github repo and travis-ci.

**Comment by robeden** [comment]
I revoked Travis' access.

**Comment by hbrands** [comment]
Ok, thanks.
I removed the Travis configuration and the webhook from this repo.
